apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-mkyq
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-mkyq
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-mkyq
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-mkyq
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-mkyq
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-pkzh-tenant/rhtap-demo-app/hacbs-test-project-mkyq@sha256:13624ac9f35beabbae74ef1f3133c98a2b05db6baae64ede33a62d5aba64d59d
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
