apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-mkyq
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-pkzh-tenant/rhtap-demo-app/hacbs-test-project-mkyq@sha256:13624ac9f35beabbae74ef1f3133c98a2b05db6baae64ede33a62d5aba64d59d
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
